import Head from 'next/head'
import Navbar from './Navbar';
import Sidebar from './Sidebar';

const Layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Rotaze</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Sidebar />
            {children}
        </div>
    );
}

export default Layout;